name: usecase
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  uuid: 4.3.3
  open_simplex_noise: 2.3.1
  synchronized: 3.1.0+1

  util:
    path: ../util

  model:
    path: ../model

  repository:
    path: ../repository

dev_dependencies:
  flutter_lints: ^3.0.1

flutter: